Add licensing info, new official patch and exits

diff --git a/lua.SlackBuild b/lua.SlackBuild
--- a/lua.SlackBuild
+++ b/lua.SlackBuild
@@ -1,12 +1,29 @@
 #!/bin/sh
 #
-# SlackBuild for lua
-# Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Slackware build script for Lua
 # Based on script of Yair K <cesium2@gmail.com>
+# Copyright (C) 2006-2008,2010,2011 Georgi D. Sotirov <gdsotirov@dir.bg>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+# 
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+#
 # Visit SlackPack at http://sotirov-bg.net/slackpack/
 #
+# $Id: lua.SlackBuild,v 1.5 2011/10/15 11:44:19 gsotirov Exp $
+#
 
-. ../slack-package.conf
+. ../../slack-package.conf
 
 NAME=lua
 VER_MAJOR=5
@@ -43,27 +60,27 @@ mkdir -p $PKG
 
 # Extract and fix source
 cd $TMP
-tar -xvf $CWD/$NAME-$VERSION.tar.gz
+tar -xvf $CWD/$NAME-$VERSION.tar.gz || exit 1
 cd $SRC
 fix_source
 
 # Apply patches
 # See http://lua-users.org/wiki/LuaPowerPatches
-patch -p0 -b -z.orig < $CWD/$NAME-$VERSION-advanced-readline.diff
-# See http://www.lua.org/ftp/patch-lua-5.1.4-2
-patch -p0 -b -z.orig < $CWD/$NAME-$VERSION-official.diff
+patch -p0 -b -z.orig < $CWD/$NAME-$VERSION-advanced-readline.diff || exit 2
+# See http://www.lua.org/ftp/patch-lua-5.1.4-3
+( cd src; patch -p0 -b -z.orig < $CWD/$NAME-$VERSION-official.diff ) || exit 2
 # To build shared library, but still link the interpreter to the static
 # one.  See http://lua-users.org/lists/lua-l/2005-11/msg00260.html
-patch -p0 -b -z.orig < $CWD/$NAME-$VERSION-shared.diff
+patch -p0 -b -z.orig < $CWD/$NAME-$VERSION-shared.diff || exit 2
 
 # Additional source modifications
 sed -e "s:\(.*LUA_ROOT\).*local.*:\1 \"/$LUA_PREFIX/\":" \
     -e "/LUA_CDIR/ s:lib:$LUA_LIB:" \
-    -i.orig src/luaconf.h
+    -i.orig src/luaconf.h || exit 3
 
 make -e -j4 \
   MYCFLAGS="-DLUA_USE_LINUX $SLKCFLAGS" \
-  linux || exit 1
+  linux || exit 4
 
 LD_LIBRARY_PATH=src make test || exit 2
 make -e \
@@ -71,7 +88,7 @@ make -e \
   INSTALL_INC=$PKG/usr/include/$NAME/${VER_MAJOR}.${VER_MINOR} \
   INSTALL_LIB=$PKG/usr/lib/$NAME/${VER_MAJOR}.${VER_MINOR} \
   INSTALL_MAN=$PKG/usr/man/man1 \
-  install || exit 3
+  install || exit 5
 
 # Link lua shared library
 ( cd $PKG/$LUA_PREFIX/$LUA_LIBDIR
@@ -143,6 +160,7 @@ install -m 644 $CWD/slack-required        $SBDIR/slack-required
 install -m 644 $CWD/$NAME-$VERSION-*.diff $SBDIR
 install -m 644 $CWD/$NAME.SlackBuild      $SBDIR/$NAME.SlackBuild
 
+# Assemble package
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
 makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
@@ -150,6 +168,7 @@ cd $PKG_DIR
 md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Clean up
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
